In [ ]:
import numpy as np

# Function to perform matrix multiplication
def matrix_multiply(A, B):
    return np.dot(A, B)

# Example matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Perform multiplication
result = matrix_multiply(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication Result:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [ ]:
data = [10, 15, 20, 25, 30]

In [ ]:
def min_max_scale(data):
    min_val = min(data)
    max_val = max(data)
    return [(x - min_val) / (max_val - min_val) for x in data]

scaled_data = min_max_scale(data)
print("Original Data:", data)
print("Min-Max Scaled Data:", scaled_data)

Original Data: [10, 15, 20, 25, 30]
Min-Max Scaled Data: [0.0, 0.25, 0.5, 0.75, 1.0]


In [ ]:
def standardize(data):
    mean = sum(data) / len(data)
    std = (sum([(x - mean) ** 2 for x in data]) / len(data)) ** 0.5
    return [(x - mean) / std for x in data]

standardized_data = standardize(data)
print("Standardized Data:", standardized_data)

Standardized Data: [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]
